In [2]:
import numpy as np

In [9]:
data=[1,2,3]

In [10]:
type(data)

list

In [17]:
arr=np.array([1,2,3,4,5])

In [18]:
arr

array([1, 2, 3, 4, 5])

# ARRAY with Zeros and Ones

In [2]:
a=np.zeros(3, dtype=int)

In [3]:
b=np.zeros([3,3], dtype=int)

In [4]:
print("Matrix a: \n",a)
print("\nMatrix b: \n",b)

Matrix a: 
 [0 0 0]

Matrix b: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
c=np.zeros([5,3], dtype=int)
print("\nMatrix c: \n",c)


Matrix c: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
d=np.ones(3, dtype=int)
print("\nMatrix d: \n",d)


Matrix d: 
 [1 1 1]


In [8]:
e=np.ones([3,5], dtype=int)
print("\nMatrix e: \n",e)


Matrix e: 
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [43]:
array = np.ones((4, 4))

In [44]:
print("Original array")
print(array)

Original array
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [46]:
print("\n0 on the border and 1 inside the array")
array = np.pad(array, pad_width=1, mode='constant',
               constant_values=0)
  
print(array)


0 on the border and 1 inside the array
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Arrays

In [19]:
import numpy

In [20]:
arr = numpy.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])

In [21]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [22]:
print([1, 2, 3, 4, 5] in arr.tolist())

True


In [23]:
print([3, 2, 5, -4, 5] in arr.tolist())

False


In [24]:
n_arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])

In [26]:
print("Given array:")
print(n_arr)

Given array:
[[10.5 22.5  3.8]
 [41.   nan  nan]]


In [27]:
print("\nRemove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr).any(axis=1)])


Remove all rows containing non-numeric elements
[[10.5 22.5  3.8]]


In [28]:
arr = numpy.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])

In [30]:
output = repr(arr).count("9, 4")
print(output)

4


In [31]:
x = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print("Original array:")
print(x)

Original array:
[1 1 1 2 3 4 2 4 3 3]


In [33]:
print("Most frequent value in above array")
y = np.bincount(x)
maximum = max(y)
for i in range(len(y)):
    if y[i] == maximum:
        print(i, end=" ")

Most frequent value in above array
1 3 

# Arrange

In [34]:
num_1d = np.arange(5)
print("One dimensional array:")
print(num_1d)

One dimensional array:
[0 1 2 3 4]


In [35]:
num_2d = np.arange(10).reshape(2,5)
print("\nTwo dimensional array:")
print(num_2d)


Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [36]:
for a, b in np.nditer([num_1d, num_2d]):
    print("%d:%d" % (a, b),)

0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


In [37]:
array_1 = np.array([1, 2])
array_2 = np.array([4, 6])

In [38]:
print("Array-1")
print(array_1)

Array-1
[1 2]


In [39]:
print("\nArray-2")
print(array_2)


Array-2
[4 6]


In [42]:
comb_array = np.array(np.meshgrid(array_1, array_2)).T.reshape(-1, 2)
print("\nCombine array:")
print(comb_array)


Combine array:
[[1 4]
 [1 6]
 [2 4]
 [2 6]]


In [47]:
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])

In [48]:
print("Array a: ", a)
print("Array b: ", b)

Array a:  [101  99  87]
Array b:  [897  97 111]


In [49]:
print("a > b")
print(np.greater(a, b))

a > b
[False  True False]


In [50]:
print("a >= b")
print(np.greater_equal(a, b))

a >= b
[False  True False]


In [51]:
print("a < b")
print(np.less(a, b))

a < b
[ True False  True]


In [52]:
print("a <= b")
print(np.less_equal(a, b))

a <= b
[ True False  True]


In [53]:
ini_array = np.array([1, 2, 3, 6, 4, 5])

In [54]:
print("initial array", str(ini_array))

initial array [1 2 3 6 4 5]


In [55]:
print("type of ini_array", type(ini_array))

type of ini_array <class 'numpy.ndarray'>


In [56]:
res = ini_array[::-1]

In [59]:
print("final array", str(res))

final array [5 4 6 3 2 1]


# Maximum and Minimum

In [66]:
gfg = np.matrix('[64, 1; 12, 3]')

In [67]:
geeks = gfg.max()
print(geeks)

64


In [68]:
gfg = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, -9]')

In [69]:
geeks = gfg.min()
print(geeks)

-9


In [70]:
gfg = np.matrix('[4, 1, 12, 3, 4, 6, 7]')

In [71]:
geek = gfg.take(2)
print(geek)

[[12]]


In [72]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

In [73]:
geek = gfg.take(0, 1)
print(geek)

[[ 4 12  4]]


# Operations on Matrix 

In [74]:
# addition of matrix
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

In [75]:
print("initial_array : ", str(ini_array));

initial_array :  [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]]


In [78]:
column_to_be_added = np.array([1, 2, 3])

In [79]:
result = np.hstack((ini_array, np.atleast_2d(column_to_be_added).T))

In [80]:
print ("resultant array", str(result))

resultant array [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


In [81]:
# matrix multiplication
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
print("Matrix p :")
print(p)
print("Matrix q :")
print(q)

Matrix p :
[[1, 2], [2, 3]]
Matrix q :
[[4, 5], [6, 7]]


In [82]:
result = np.dot(p, q)

In [83]:
print("The matrix multiplication is :")
print(result)

The matrix multiplication is :
[[16 19]
 [26 31]]


In [84]:
# inverse of a matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

In [85]:
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [86]:
#convert matrix into list
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

In [87]:
geek = gfg.tolist()
print(geek)

[[4, 1, 9], [12, 3, 1], [4, 5, 6]]


# Indexing

In [7]:
n_arr = np.array([75.42436315, 42.48558583, 60.32924763])
print("Given array:")
print(n_arr)

Given array:
[75.42436315 42.48558583 60.32924763]


In [4]:
print("\nReplace all elements of array which are greater than 50. to 15.50")
n_arr[n_arr > 50.] = 15.50
print("New array :\n")
print(n_arr)  


Replace all elements of array which are greater than 50. to 15.50
New array :

[15.5        42.48558583 15.5       ]


In [8]:
np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]], [[5, 6], [7, 8]])

array([[1, 6],
       [3, 4]])

In [10]:
ini_array = np.array([[1.3, 2.5, 3.6, np.nan], 
                      [2.6, 3.3, np.nan, 5.5],
                      [2.1, 3.2, 5.4, 6.5]])
print ("initial array", ini_array)

initial array [[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]]


In [11]:
col_mean = np.nanmean(ini_array, axis = 0)
print ("columns mean", str(col_mean))

columns mean [2.  3.  4.5 6. ]


In [12]:
inds = np.where(np.isnan(ini_array))
ini_array[inds] = np.take(col_mean, inds[1])

In [13]:
print ("final array", ini_array)

final array [[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


In [14]:
ini_array1 = np.array([1, 2, -3, 4, -5, -6])
print("initial array", ini_array1)

initial array [ 1  2 -3  4 -5 -6]


In [15]:
ini_array1[ini_array1<0] = 0
print("New resulting array: ", ini_array1)

New resulting array:  [1 2 0 4 0 0]


In [16]:
a1 = np.array([11, 10, 22, 30, 33])
print("Array 1 :")
print(a1)

Array 1 :
[11 10 22 30 33]


In [17]:
a2 = np.array([1, 15, 60])
print("Array 2 :")
print(a2)

Array 2 :
[ 1 15 60]


In [18]:
print("\nTake 1 and 15 from Array 2 and put them in\
1st and 5th position of Array 1")  
a1.put([0, 4], a2)
print("Resultant Array :")
print(a1)


Take 1 and 15 from Array 2 and put them in1st and 5th position of Array 1
Resultant Array :
[ 1 10 22 30 15]


In [19]:
gfg1 = np.array([1, 2, 3, 4, 5])
lis = [1, 3, 5]
gfg = np.isin(gfg1, lis)
print(gfg)

[ True False  True False  True]


In [20]:
gfg1 = np.array([1, 2, 3])
gfg2 = np.array([4, 5, 6])

In [21]:
print(np.dstack((gfg1, gfg2)))

[[[1 4]
  [2 5]
  [3 6]]]


# Random

In [27]:
#numpy array with random values
x = np.empty(2, dtype = int) 
print("Matrix x : \n", x) 
y = np.empty([2, 2], dtype = int) 
print("\nMatrix y : \n", y) 

Matrix x : 
 [0 0]

Matrix y : 
 [[3 0]
 [2 0]]


In [32]:
np.random.rand(2)

array([0.3271747 , 0.73056922])

In [34]:
import random
sampleList = [100, 200, 300, 400, 500]
randomList = random.choices(
    sampleList, weights=(10, 20, 30, 40, 50), k=5)
print(randomList)

[300, 500, 200, 500, 500]


In [37]:
import numpy.matlib
out_mat = np.matlib.rand((3, 4)) 
print ("Output matrix : ", out_mat) 

Output matrix :  [[0.83686329 0.00803962 0.15611178 0.17069949]
 [0.40518989 0.45812958 0.66917027 0.42147707]
 [0.84100591 0.78009372 0.84880026 0.37241417]]


In [38]:
np.random.randint(2,25)

14