In [5]:
def swapList(newList):
    size = len(newList)
     
    # Swapping
    temp = newList[0]
    newList[0] = newList[size - 1]
    newList[size - 1] = temp
     
    return newList

In [6]:
newList = [12, 35, 9, 56, 24]
print(swapList(newList))

[24, 35, 9, 56, 12]


In [7]:
list = [1, 2, 3, 4]
a, *b, c = list
print(a)
print(b)
print(c)

1
[2, 3]
4


In [11]:
def swapPositions(list, pos1, pos2):
    list[pos1], list[pos2] = list[pos2], list[pos1]
    return list
 # Driver function
List = [23, 65, 19, 90]
pos1, pos2  = 1, 3
print(swapPositions(List, pos1-1, pos2-1))

[19, 65, 23, 90]


In [12]:
a = []
a.append("Hello")
a.append("Geeks")
a.append("For")
a.append("Geeks")
print("The length of list is: ", len(a))

The length of list is:  4


In [18]:
 
def maximum(a, b):
     
    if a >= b:
        return a
    else:
        return b
     
a = 2
b = 4
print(maximum(a, b))

4


In [19]:
def minimum(a, b):
      
    if a <= b:
        return a
    else:
        return b
      
a = 2
b = 4
print(minimum(a, b))

2


In [20]:
def rev_sentence(sentence): 
  
    words = sentence.split(' ') 
  
    reverse_sentence = ' '.join(reversed(words)) 
  
    return reverse_sentence 
  
if __name__ == "__main__": 
    input = 'lets learn machine learning'
    print (rev_sentence(input))

learning machine learn lets


In [21]:
def printWords(s):
      
    s = s.split(' ') 
      
    for word in s: 
          
        if len(word)%2==0:
            print(word) 
  
s = "i am muskan" 
printWords(s) 

am
muskan


In [22]:
list1 = [1, 2, 5, 6]
res = [(val, pow(val, 3)) for val in list1]
print(res)

[(1, 1), (2, 8), (5, 125), (6, 216)]


In [24]:
country_code = {'India' : '0091',
                'Australia' : '0025',
                'Nepal' : '00977'}
print(country_code.get('India', 'Not Found'))

0091


In [25]:
print(country_code.get('Japan', 'Not Found'))

Not Found


In [26]:
import random as rn

In [27]:
dict = {}

x, y, z = 10, 20, 30
dict[x, y, z] = x + y - z;
x, y, z = 5, 2, 4
dict[x, y, z] = x + y - z;
print(dict)

{(10, 20, 30): 0, (5, 2, 4): 3}


In [29]:
import sys
Set1 = {"A", 1, "B", 2, "C", 3}
Set2 = {"Geek1", "Raju", "Geek2", "Nikhil", "Geek3", "Deepanshu"}
Set3 = {(1, "Lion"), ( 2, "Tiger"), (3, "Fox")}
  
# print the sizes of sample Sets
print("Size of Set1: " + str(sys.getsizeof(Set1)) + "bytes")
print("Size of Set2: " + str(sys.getsizeof(Set2)) + "bytes")
print("Size of Set3: " + str(sys.getsizeof(Set3)) + "bytes")

Size of Set1: 728bytes
Size of Set2: 728bytes
Size of Set3: 216bytes


In [30]:
def MAX(sets):
    return (max(sets))
sets = set([8, 16, 24, 1, 25, 3, 10, 65, 55])
print(MAX(sets))

65


In [31]:
def Remove(initial_set):
    while initial_set:
        initial_set.pop()
        print(initial_set)
initial_set = set([12, 10, 13, 15, 8, 9])
Remove(initial_set)

{9, 10, 12, 13, 15}
{10, 12, 13, 15}
{12, 13, 15}
{13, 15}
{15}
set()


In [32]:
import numpy as np

In [33]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [34]:
print("Subtraction of two matrix")
print(np.subtract(A, B))

Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [39]:
import itertools
def sub_mat_even(n):
    temp = itertools.count(1)
    l = [[next(temp)for i in range(n)]for i in range(n)]
    if n%2 == 0:
        for i in range(0,len(l)):
            if i%2 == 1:
                l[i][:] = l[i][::-1]
    for i in range(n):
        for j in range(n):
            print(l[i][j],end=" ")
        print()
n = 4
sub_mat_even(n)

1 2 3 4 
8 7 6 5 
9 10 11 12 
16 15 14 13 


In [40]:
class oops:
    pass
obj = oops()
  
print(obj)

In [41]:
class Employee:
    pass
obj1 = Employee()
obj1.name = 'Nikhil'
obj1.office = 'GeeksforGeeks'
obj2 = Employee()
obj2.name = 'Abhinav'
obj2.office = 'GeeksforGeeks'
obj2.phone = 1234567889
print("obj1 Details:")
print("Name:", obj1.name)
print("Office:", obj1.office)
print()
print("obj2 Details:")
print("Name:", obj2.name)
print("Office:", obj2.office)
print("Phone:", obj2.phone)

obj1 Details:
Name: Nikhil
Office: GeeksforGeeks

obj2 Details:
Name: Abhinav
Office: GeeksforGeeks
Phone: 1234567889


In [42]:
from datetime import *
import pytz
  
  
tz_INDIA = pytz.timezone('Asia/Kolkata') 
datetime_INDIA = datetime.now(tz_INDIA)
print("INDIA time:", datetime_INDIA.strftime("%H:%M:%S"))

INDIA time: 18:22:39


In [43]:
from datetime import datetime
now_method = datetime.now()
currentTime = now_method.strftime("%H:%M:%S")
print("Current Time =", currentTime)

Current Time = 18:23:39
